version: '3.8'
services:
  db_postgres:
    image: postgres:latest
    container_name: docker_postgres
    environment:
      - POSTGRES_USER='postgres'
      - POSTGRES_PASSWORD='postgres'
      - POSTGRES_DB='users'
      - POSTGRES_HOST='localhost'
    ports:
      - '5400:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack

  app:
    container_name: docker_crud
    build: .
    ports: 
      - '8081:8080' 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - db_postgres         
    networks:
      - fullstack

volumes:
  api:
  database_postgres:
    driver: local          

networks:
  fullstack:
    driver: bridge

