version: '3.8'
networks:
  connect: 
    driver: bridge
services:
  db_postgres:
    image: postgres:latest
    container_name: docker_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    ports:
      - '5400:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - connect
  app:
    container_name: docker_crud
    image: 
    build: .
    ports: 
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - db_postgres
    networks:
      - connect
volumes:
  api:
  database_postgres:
    driver: local          

