version: '3.8'
networks:
  test_docker:
    driver: bridge
services:
  app: 
    container_name: web_api
    build: .
    ports: 
      - "8080:8080"
    volumes: 
      - api:/var/snap/docker/common/var-lib-docker/volumes/api
    depends_on:
      - db
    networks:
      - test_docker
  db: 
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
      - POSTGRES_HOST="localhost"
    networks:
      - test_docker
volumes:
 api:
 db:
 

